name: Merge
on:
  pull_request:
    branches:
      - master
jobs:
  linting:
    runs-on: Large-Runner
    env:
      COMPOSE_FILE: docker/docker-compose.local.yml
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build lint image
        run: docker-compose build lint
      - name: Run Linting
        run: docker-compose run lint
  testing:
    runs-on: Large-Runner
    env:
      COMPOSE_FILE: docker/docker-compose.local.yml
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build test image
        run: docker-compose build tests
      - name: Run tests
        run: docker-compose run tests